### ISSUE TITLE
Allow users to set their own assets base path

### ISSUE THREAD

**Issue by imaNNeo** [manjav/particular#12]
At the moment, we expect that the texture file is inside the root of our `assets/`, but int most cases, we have different directories for our assets. So I think it makes sense to allow user to set the default path for the particular assets.

https://github.com/manjav/particular/blob/f522112486b41222175f38986644365083dda266/lib/src/particular_controller.dart#L191-L192

And also, I think we can have the default path like this: `assets/particular/`

**Comment by manjav** [comment]
This feature added on custom layer label
