### ISSUE TITLE
Import a zip file (that we already exported)

### ISSUE THREAD

**Issue by imaNNeo** [manjav/particular#15]
Sometimes we need to share the particle that we created and exported to others,
Then they can import and work on it.
So we need to have a feature in Particular to allow us to import a zip file (which contains the JSON file and also the textures)

Or maybe we can have our own file type to write the JSON content + textures inside it (as a base64 or raw bytes)

**Comment by manjav** [comment]
For holding away unnecessary texture bytes from plugin (memory usage)
