### ISSUE TITLE
How to interpolate from start point to end point

### ISSUE THREAD

**Issue by Ahmadre** [manjav/particular#2]
Thank you so much for this awesome package ❤️ 

Because I cannot find any documentation about it: can I tween from a given point to an endpoint?

Like: from a Flutter screenpoint `Vector2 start = Vector2(0, 0)` ➡️ `Vector2 start = Vector2(100, 100)` inside the Dart Code?

I want to have particles and dynamically interpolate that particles inside of my app. How can I achieve this?

Thank you for your answer :)

**Comment by manjav** [comment]
Sure
You can update`emitterX` and `emitterY`  in tween tools callback like in `onPanUpdate` in bellow code 

https://github.com/manjav/particular/blob/3f6b13a4966e61e7f332f4caa82b89d7d369d86b/editor/lib/main.dart#L112

**Comment by Ahmadre** [comment]
This is not the answer I was looking for...

You are directing to an example where you use `onPanUpdate` to make changes, but I want to do that by a function like a one-time animation without the user doing something.

**Comment by manjav** [comment]
OK. I understand but I prefer Particular stay minimal. I can provide simple code for you

**Comment by Ahmadre** [comment]
> OK. I understand but I prefer Particular stay minimal. I can provide simple code for you

no it's fine I don't want any example code :). Maybe this package is still under development and not ready yet with full documentation.

Have a nice day!

**Comment by manjav** [comment]
I am working on docs
Thanks

**Comment by Ahmadre** [comment]
> Sure You can update`emitterX` and `emitterY` in tween tools callback like in `onPanUpdate` in bellow code
> 
> https://github.com/manjav/particular/blob/3f6b13a4966e61e7f332f4caa82b89d7d369d86b/editor/lib/main.dart#L112

I managed to build particular and got this working :) thank you so much for your answer! I will try to contribute to this awesome package ❤️
