### ISSUE TITLE
Outdated Readme

### ISSUE THREAD

**Issue by Ahmadre** [manjav/particular#4]
I tried out your package, but all interfaces mentioned in the Readme are outdated 😅 I don't know how to use this public package...

For example: there's no texture attribute for `addLayer`...
There's no update method for a partical layer...

**Comment by manjav** [comment]
Thanks for your issue. It will update as soon as possible and will put in future tests. Please use the example and editor side-apps in the github project. Also I will update docs in 1-2 days.
